In [1]:
%pip install Pytorch


  Running setup.py clean for Pytorch
Failed to build Pytorch
    Running setup.py install for Pytorch: started
    Running setup.py install for Pytorch: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  ERROR: Command errored out with exit status 1:
   command: 'c:\Users\keb20\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\keb20\\AppData\\Local\\Temp\\pip-install-bfpsbqn7\\pytorch_ec4357f196d1409db993c52f63b76c4b\\setup.py'"'"'; __file__='"'"'C:\\Users\\keb20\\AppData\\Local\\Temp\\pip-install-bfpsbqn7\\pytorch_ec4357f196d1409db993c52f63b76c4b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\keb20\AppData\Local\Temp\pip-wheel-l3ulq6id'
       cwd: C:\Users\keb20\AppData\Local\Temp\pip-install-bfpsbqn7\pytorch_ec4357f196d1409db993c52f63b76c4b\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\keb20\AppData\Loca

In [2]:
%pip install tqdm

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
scalar = 0
np_scalar = np.array(scalar)
np_scalar, np_scalar.dtype

(array(0), dtype('int32'))

In [5]:
scalar = range(10)
np_scalar = np.array(scalar)
np_scalar, np_scalar.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [8]:
# comprehension 응용
scalar = [[float(j) for j in range(_+10)] for _ in range(10)]
np_scalar = np.array(scalar)
np_scalar, np_scalar.dtype

C:\Users\keb20\AppData\Local\Temp/ipykernel_23928/3945050948.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np_scalar = np.array(scalar)


(array([list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0]),
        list([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0])],
       dtype=object),
 dtype('O'))

In [9]:
# numpy이기 때문에 연산됨
scalar = [[float(j) for j in range(_, _+10)] for _ in range(10)]
np_scalar = np.array(scalar)
np_scalar, np_scalar.dtype

(array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
        [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
        [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
        [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
        [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]]),
 dtype('float64'))

In [15]:
random_noise_generator_fn = lambda : np.random.normal(size = (3))
scalar = [
    np.array([random_noise_generator_fn() for _ in range(4)]) for _ in range(5)
]
print(scalar)
print([i.shape for i in scalar])

[array([[-0.3202145 ,  0.47540751,  0.64061335],
       [ 0.41199192, -0.89194632, -1.64233215],
       [-1.71805183, -1.20143942,  0.32993002],
       [ 2.37347204,  1.93829501,  0.97694795]]), array([[ 0.67156116, -1.10638357,  0.38899211],
       [-1.37840093,  0.15407509, -1.17712069],
       [-0.86886878, -0.57801257,  0.71042913],
       [-0.0839646 , -1.33472568,  0.42824481]]), array([[ 0.40132371, -0.98591586,  1.54307014],
       [ 0.47638338,  0.15047493, -0.15166019],
       [ 0.73893949,  1.07182624,  2.18618682],
       [ 0.16352171, -1.1532184 , -0.11264096]]), array([[ 0.84116529, -0.17855695,  0.27832417],
       [ 0.10487891,  0.81223989,  0.48472413],
       [-2.25777161,  0.69206855,  0.44470095],
       [ 0.35598799,  0.30953112, -1.68392613]]), array([[-2.25690429, -1.78846832,  0.34520411],
       [-1.05779663, -0.5239075 ,  0.10036649],
       [-0.01571441, -0.07391123,  0.87802326],
       [ 1.63333793, -1.03911344, -0.22777274]])]
[(4, 3), (4, 3), (4, 3), (4, 

In [16]:
# concatenate
np_scalar = np.array(scalar)
print(np_scalar.shape, np_scalar.dtype)

np_concat_0_scalar = np.concatenate(scalar, 0)
print(np_concat_0_scalar.shape)

np_concat_1_scalar = np.concatenate(scalar, 1)
print(np_concat_1_scalar.shape)

(5, 4, 3) float64
(20, 3)
(4, 15)


In [17]:
np_scalar[: , 1]
np_concat_0_scalar[1::4]

array([[ 0.41199192, -0.89194632, -1.64233215],
       [-1.37840093,  0.15407509, -1.17712069],
       [ 0.47638338,  0.15047493, -0.15166019],
       [ 0.10487891,  0.81223989,  0.48472413],
       [-1.05779663, -0.5239075 ,  0.10036649]])

In [20]:
# stack
np_scalar = np.array(scalar)
print(np_scalar.shape, np_scalar.dtype)

np_stack_0_scalar = np.stack(scalar,0)
print(np_stack_0_scalar.shape)

np_stack_1_scalar = np.stack(scalar,1)
print(np_stack_1_scalar.shape)

np_stack_2_scalar = np.stack(scalar,2)
print(np_stack_2_scalar.shape)

(5, 4, 3) float64
(5, 4, 3)
(4, 5, 3)
(4, 3, 5)


In [22]:
tensor_a = np.random.normal(size = (4, 3, 2))
tensor_b = np.random.normal(size = (4, 3, 2))

add_tensor_ab = tensor_a + tensor_b
print(add_tensor_ab)
add_tensor_ab = np.add(tensor_a, tensor_b)
print(add_tensor_ab)

[[[ 1.40286993 -1.0138989 ]
  [-1.01489008 -1.25155204]
  [-0.75571886 -0.28872708]]

 [[ 0.41583214 -0.99930586]
  [-0.59133086  1.05585783]
  [ 3.76699349  3.10750404]]

 [[-0.10794596 -0.68732542]
  [ 0.02979498 -3.79972481]
  [ 1.16513951 -1.31248782]]

 [[ 0.5990825   1.76113941]
  [ 1.87326484  1.05609846]
  [-0.60595014 -1.87283538]]]
[[[ 1.40286993 -1.0138989 ]
  [-1.01489008 -1.25155204]
  [-0.75571886 -0.28872708]]

 [[ 0.41583214 -0.99930586]
  [-0.59133086  1.05585783]
  [ 3.76699349  3.10750404]]

 [[-0.10794596 -0.68732542]
  [ 0.02979498 -3.79972481]
  [ 1.16513951 -1.31248782]]

 [[ 0.5990825   1.76113941]
  [ 1.87326484  1.05609846]
  [-0.60595014 -1.87283538]]]


In [ ]:
# substract
# divide
# matmul(inner product) @
# transpose() 전치
# np.linalg.inv() 역행렬

In [23]:
import pandas as pd

load_Iris = pd.read_csv('./files/Week02_iris_w_missing.csv')
load_Iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                NaN               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [25]:
# loc index key에 0이 존재하게 됨
load_Iris.loc[0]
# iloc을 사용하는 경우 인덱스로 따라가게 됨

sepal length (cm)       5.1
sepal width (cm)        3.5
petal length (cm)       1.4
petal width (cm)        0.2
target               setosa
Name: 0, dtype: object

In [24]:
# 결측치 제어방법 : 제거 & 보간
print(load_Iris.info())
print(load_Iris.dropna(axis = 0).info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  144 non-null    float64
 1   sepal width (cm)   140 non-null    float64
 2   petal length (cm)  145 non-null    float64
 3   petal width (cm)   141 non-null    float64
 4   target             150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 122 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  122 non-null    float64
 1   sepal width (cm)   122 non-null    float64
 2   petal length (cm)  122 non-null    float64
 3   petal width (cm)   122 non-null    float64
 4   target             122 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.7+ KB
None


In [27]:
# normalize
mean, std = load_Iris.mean(), load_Iris.std()
normal_load_Iris = (load_Iris.iloc[:, :-1] - mean) / std
print(load_Iris.describe())
print(normal_load_Iris.describe())

       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         144.000000        140.000000         145.000000   
mean            5.845833          3.060000           3.713103   
std             0.837485          0.434286           1.767030   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.500000   
50%             5.800000          3.000000           4.300000   
75%             6.400000          3.325000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        141.000000  
mean           1.204965  
std            0.767401  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000  
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.440000e+02      1.400000e+02       1.450000e+02   
mean       -1.664371e-16     -3.176626e-15      -1

C:\Users\keb20\AppData\Local\Temp/ipykernel_23928/4194830812.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mean, std = load_Iris.mean(), load_Iris.std()


In [31]:
# value Encoding

# Label encoding
Iris_target_dict = {i:n for n, i in enumerate(load_Iris.target.unique())}
Iris_label_encoding = load_Iris.target.apply(lambda x : Iris_target_dict[x])
Iris_label_encoding

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [32]:
# Binary encoding
def int2byte(x):
    return x % 2, x // 2
Iris_binary_encoding = Iris_label_encoding.apply(lambda x:int2byte(x+1))
Iris_binary_encoding

0      (1, 0)
1      (1, 0)
2      (1, 0)
3      (1, 0)
4      (1, 0)
        ...  
145    (1, 1)
146    (1, 1)
147    (1, 1)
148    (1, 1)
149    (1, 1)
Name: target, Length: 150, dtype: object

In [33]:
# one-hot encoding
Iris_onehot_encoding = np.eye(3)[Iris_label_encoding]
Iris_onehot_encoding

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0